language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip
matrix:
  allow_failures:
      - go: tip

before_install:
  - go get github.com/mattn/gom
install:
  - bash install.sh
script:
  - $HOME/gopath/bin/gom install
  - $HOME/gopath/bin/gom test -run "Test*" # ingore example test... :<

after_script:
  - go get github.com/cosmo0920/tesseractocr-capi-go
  - gom build example/sample.go
  - gom build example/sample_basic.go
  - gom build example/sample_specify_oem.go